repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-absolute-import
        - flake8-black
        #- flake8-docstrings
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: master
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-merge-conflict
    - id: detect-aws-credentials