repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args:
        - --check
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: master
    hooks:
    - id: detect-aws-credentials